### ISSUE TITLE
[Bug Report]: 缩放快捷键 CTRL + 滚轮会触发浏览器事件（使用选区当框选后） 

### ISSUE THREAD

**Issue by WangJincheng4869** [didi/LogicFlow#1423]
### 发生了什么？

未框选状态下可以使用 CTRL + 滚轮 对画布进行缩放。
![动画](https://github.com/didi/LogicFlow/assets/41162158/770265ba-2472-40cf-a57c-4efc18a3ff5a)

当框选后，把鼠标放在框选区域就会触发浏览器自带的缩放事件，猜测应该是框选样式的 div 未处理事件穿透。

ps：目前我是通过添加自定义样式 `pointer-events: none;` 解决
```css
.lf-multiple-select {
  pointer-events: none;
}
```

### logicflow/core版本

1.2.17

### logicflow/extension版本

1.2.18

### logicflow/engine版本

未使用

### 浏览器&环境

Chrome
