### ISSUE TITLE
[Bug Report]: 变更窗口大小后添加节点，小地图显示异常

### ISSUE THREAD

**Issue by EdwinOlders11** [didi/LogicFlow#2017]
### 发生了什么？

变更窗口大小后添加节点，小地图显示异常，
复现：https://codesandbox.io/p/sandbox/debugdemo-shvsw2
拖动窗口大小后再点击add node，小地图显示异常，回退到2.0.9版本则没有此问题

顺便想问一下lf支持的浏览器最低版本？在官网文档和git上都没有找到..最近有个项目需要兼容win7，我自己测试chrome109还能用，到107就不行了...还好109就是win7上支持的最高的版本

### logicflow/core版本

2.0.10

### logicflow/extension版本

2.0.14

### 浏览器&环境

Chrome, NodeJS

**Comment by ChangeSuger** [comment]
这个和两个版本之间新增的根据窗口变化的同步画布大小的改动有关，因为小地图的缩放有一部分是基于父元素的 `transform` 属性实现的，因此，小地图中 LF 画布的父元素的真实高宽是远大于 `getBoundingClientRect()` 获取的父元素高宽的，这导致了现在这个问题。

修复方法的话就是强制样式覆盖，只需要添加如下样式就行：

```css
.lf-mini-map .lf-graph {
  width: 100% !important;
  height: 100% !important;
}
```

不过可能该改动上线可能需要等新版本的发布，需要一段时间，在此之前可以先通过手动添加这个全局样式暂时解决这个问题~
