### ISSUE TITLE
动态改变拖拽面板样式

### ISSUE THREAD

**Issue by MvCraK** [didi/LogicFlow#433]
动态改变拖拽面板，以框选举例

期望效果：开启框选后，拖拽面板中框选图片变成B，关闭框选后，拖拽面板中框选图片变为A。从而让用户能一眼看出当前是否开启框选

**Comment by towersxu** [comment]
目前不支持直接修改，有迂回的方法，后续考虑在拖拽面板上扩展此功能：

拖拽面板支持传入className。你可以选择传入一个自定义的class， 假设custom-selection-cls。然后，当开启选框的时候，也就是callback触发的时候，你在LogicFlow的container上多加一个class, 假设为selection-model-cls。这个时候就可以通过css强制覆盖拖拽面板的基础样式了。
```css
.selection-model-cls .custom-selection-cls {
   background-image: ""
}
```
