### ISSUE TITLE
关于文字旋转的实现

### ISSUE THREAD

**Issue by chendx79** [didi/LogicFlow#540]
为了实现在竖直状态下的连线旁边的文字注释。想问问应该怎样实现以下几个步骤：
当文字旋转90度的时候，我需要：、
1.修改text的transform="rotate(-90)"
2.根据文字的长度来调整outline的宽和高，分别为之前的高和宽。
3.根据文字的长度来调整rect的宽和高，分别为之前的高和宽。
4.修改text的transform="translate(x,y) rotate(-90)"， 里面的x=outline.x + outline.width/2， x=outline.y + outline.height/2

请说说在在mvp项目下应该怎样修改，谢谢。

**Comment by chendx79** [comment]
在TextNode上怎样修改？

**Comment by towersxu** [comment]
可以用css控制，css文本中心旋转90度可以这样写
```css
.element {
    transform-box: fill-box;
    transform-origin: center;
    transform: rotate(90deg);
}
```
