### ISSUE TITLE
开启边动画在某些项目中动画效果错误

### ISSUE THREAD

**Issue by towersxu** [didi/LogicFlow#840]
由于内置的动画名称为`dash`, 很容易和大多数项目的动画冲突，导致动画效果异常。所以需要修改动画名称为`lf_animate_dash`，来避免冲突。

对于使用之前版本的，可以先强制覆盖`.lf-edge-animation`的animation来解决这个问题。

1. 在自定义动画的时候，增加animationName属性，自定义一个动画名称。
```js
getEdgeAnimationStyle() {
    const style = super.getEdgeAnimationStyle();
    style.strokeDasharray = "5 5";
    style.animationDuration = "10s";
    style.animationName = "lf_animate_dash"
    return style;
  }
```

2. 然后在全局css中增加自定义动画效果。
```css
@keyframes lf_animate_dash {
  to {
    stroke-dashoffset: 0;
  }
}
```
