### ISSUE TITLE
[Bug report]继承HtmlNodeModel组件存在莫名的边框问题

### ISSUE THREAD

**Issue by shanquanyaoyue** [didi/LogicFlow#919]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件 继承 HtmlNodeModel 通过 React 声明自定义组件样式
2. 期望的表现 期望选中时根据自定义样式展示
3. 实际的表现 有默认边框问题
![20221205135403_rec_](https://user-images.githubusercontent.com/111632046/205559667-748b2072-9dae-47ec-bb0b-d2b34e185f39.gif)

[**最简复现demo**  
https://codesandbox.io/s/stoic-parm-xjzt3e?file=/src/index.js

**Comment by shanquanyaoyue** [comment]
添加样式解决：

```css
foreignObject{
    overflow: visible;
    outline: none;
}
```
